name : Terraform_deploy
on:
  push:
    branches:
    - 'main'
  workflow_dispatch:  

jobs:
  _build_:
    name : build_app_image
    runs-on: ubuntu-latest
    environment: DEV
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPO:  ${{ secrets.REPO }}
    steps:
    - uses: actions/checkout@v6
    - name: install docker AWS CLI
      run: |
       curl -fsSL https://get.docker.com -o get-docker.sh && \
       sh get-docker.sh && \
       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
       unzip awscliv2.zip && \
       ./aws/install
    - name: build  
      run: docker build -t $REPO:1.0 .
    - name: push image
      run: |
        aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $REPO && \
        docker push $REPO:1.0


  _fmt_:
    name: fmt
    runs-on: ubuntu-latest
    environment: DEV
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    container:
      image: hashicorp/terraform:latest
    steps:
    - uses: actions/checkout@v6
    - name : init 
      run : terraform init 
    - name: fmt
      run : terraform fmt --recursive
    - uses: actions/upload-artifact@v7
      with:
        name: fmt
        path: .  
    needs: _build_

  _validate_:
    name: validate
    runs-on: ubuntu-latest
    environment: DEV
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
    container:
      image: hashicorp/terraform:latest 
    steps:
    - uses: actions/download-artifact@v7
      with:
        name: fmt
    - name: init 
      run: terraform init
    - name: validate
      run: terraform validate
    - uses: actions/upload-artifact@v7
      with:
        name: validate
        path: .  
    needs: _fmt_  
  
  _plan_:
    name: plan
    runs-on: ubuntu-latest
    environment: DEV
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    container:
      image: hashicorp/terraform:latest
    steps:
    - uses: actions/download-artifact@v7
      with:
        name: validate
    - name: init 
      run: terraform init
    - name: plan
      run: terraform plan -out=myplan
    - uses: actions/upload-artifact@v7
      with:
        name: myplan
        path: .
      

    needs: _validate_  

  _apply_:
    name: apply
    runs-on: ubuntu-latest
    environment: PRD
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    container:
      image: hashicorp/terraform:latest  
    steps:
    - uses: actions/download-artifact@v7
      with:
        name: myplan
    - name: init 
      run: terraform init
    - name: apply
      run: terraform apply myplan
    needs: _plan_        